/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityManagement: typeof import('./src/components/marketing/ActivityManagement.vue')['default']
    AiCart: typeof import('./src/components/AIChat/ai-cart.vue')['default']
    AiChat: typeof import('./src/components/AIChat/ai-chat.vue')['default']
    ChartSection: typeof import('./src/components/dashboard/ChartSection.vue')['default']
    DashboardHeader: typeof import('./src/components/dashboard/DashboardHeader.vue')['default']
    DataIntegration: typeof import('./src/components/data-source/DataIntegration.vue')['default']
    EffectAnalysis: typeof import('./src/components/marketing/EffectAnalysis.vue')['default']
    EmotionDistribution: typeof import('./src/components/dashboard/EmotionDistribution.vue')['default']
    IMaterialSymbolsMenu: typeof import('~icons/material-symbols/menu.vue')['default']
    InsightSummary: typeof import('./src/components/dashboard/InsightSummary.vue')['default']
    IntelligenceInsights: typeof import('./src/components/marketing/IntelligenceInsights.vue')['default']
    MarketingEffect: typeof import('./src/components/dashboard/MarketingEffect.vue')['default']
    Mdicon: typeof import('./src/components/mdicon.vue')['default']
    MonitoringConfig: typeof import('./src/components/data-source/MonitoringConfig.vue')['default']
    MonitoringDashboard: typeof import('./src/components/data-source/MonitoringDashboard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PosDataVisualization: typeof import('./src/components/pos-data-visualization.vue')['default']
    QualityAnalysis: typeof import('./src/components/data-source/QualityAnalysis.vue')['default']
    RealTimeStream: typeof import('./src/components/dashboard/RealTimeStream.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./src/components/dashboard/StatsGrid.vue')['default']
    StrategyRecommendation: typeof import('./src/components/marketing/StrategyRecommendation.vue')['default']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TComment: typeof import('tdesign-vue-next')['Comment']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TransactionDetails: typeof import('./src/components/dashboard/TransactionDetails.vue')['default']
    TransactionOverview: typeof import('./src/components/dashboard/TransactionOverview.vue')['default']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
